title: Anegama Lahari
description: My Portfolio
url: "https://laharianegama.github.io/portfolio/"
theme: jekyll-theme-minimal
logo: headshot1.jpg
email: youremail@example.com

social:
  - icon: fab fa-linkedin
    text: LinkedIn
    url: https://www.linkedin.com/in/lahari-anegama-a9a583192/
  - icon: fab fa-github
    text: GitHub
    url: https://github.com/laharianegama

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
  

defaults:
  - scope:
      path: ""
    values:
      image: headshot1.jpg

collections:
  projects:
    output: true

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown

kramdown:
  input: GFM

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
